//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaundryApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.ComponentModel.DataAnnotations;
    public partial class OnlineOrder
    {
        public int Ord_Id { get; set; }
        
        public Nullable<int> CusIDFk { get; set; }

        
        public Nullable<int> CatIDFK { get; set; }

        
        public Nullable<int> PayIDFk { get; set; }

        [Display(Name ="Category Discription")]
        public string Cat_Des { get; set; }

        [Display(Name ="Payment Discription")]
        public string Pay_Des { get; set; }

        [Display(Name ="Item Quantity")]
        public Nullable<int> Item_Quantity { get; set; }
        public Nullable<int> Amount { get; set; }

        [Display(Name ="Payment Status")]
        public string Pay_Status { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
